[tool.black]
line-length = 88
target-version = ["py310"]
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | _build
  | env
  | .venv
  | staticfiles
)/
'''

[tool.flake8]
max-line-length = 88
exclude = ["__pycache__", "env", ".venv"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
strict_optional = true
check_untyped_defs = true
disallow_untyped_calls = true
warn_unused_ignores = true