class Categories:
    FOOD: str = "food"
    TRANSPORTATION: str = "transportation"
    HOUSING: str = "housing"
    UTILITIES: str = "utilities"
    HEALTHCARE: str = "healthcare"
    ENTERTAINMENT: str = "entertainment"
    EDUCATION: str = "education"
    SHOPPING: str = "shopping"
    SAVINGS: str = "savings"
    OTHERS: str = "others"
